export const mapConfig = {
  cper: "CPER",
  eurusd: "EURUSD=X",
  cnyeur: "CNYEUR=X",
  chefeur: "CHFEUR=X",
  btcusd: "BTC-USD",
  gsps: "^GSPC ",
  ftsmib: "FTSEMIB.MI",
  btp10: "BTP10.MI",
  crudeoil: "CL=F",
  silver: "SI=F",
  gold: "GC=F",
  palladium: "PA=F",
  hangseng: "^HSI",
  euribor3m: "EURIBOR3M",
  euriborbce: "EURIBORBCE",
  spreadbtpvsbound10y: "SPREADBTPVSBOUND10Y",
  aluminium: "ALUMINIUM",
  ttfnaturalgasfu: "TTFNATURALGASFU",
};
